In [2]:
import pandas as pd

## Special Characters in Usernames and Passwords

In [88]:
# read csv with special characters from local file
# if not: read from internet

try:
    df = pd.read_csv("data/spec_char.csv")
except:
    url = "https://support.brightcove.com/special-characters-usernames-and-passwords"
    df = pd.read_html(url)[0] #scrape from wikipedia

In [72]:
def convert_html(string_to_encode):
    
    """ðŸ§¦ converts string to 'HTML-save' string by replacing special characters"""
    
    string=""
    
    for letter in string_to_encode:
        
        if letter in list(df["Character"]):
            string = string + df[df["Character"]==letter]["Percent-Encoded"].values[0]
            
        else:
            string = string+letter
            
    return string

In [89]:
convert_html("1ze<A<GI0AE4,!6820*7pg")

found
found
found
found

'1ze%3CA%3CGI0AE4,%216820%2A7pg'

In [90]:
df

   Character Percent-Encoded
0          ]             %5B
1          [             %5D
2          ?             %3F
3          /             %2F
4          <             %3C
5          ~             %7E
6          #             %23
7          `             %6D
8          !             %21
9          @             %40
10         $             %24
11         %             %25
12         ^             %5E
13         &             %26
14         *             %2A
15         (             %28
16         )             %29
17         +             %2B
18         =             %3D
19         }             %7D
20         |             %7C
21         :             %3A
22         "             %22
23         ;             %3B
24         '             %27
25       NaN             %2C
26         >             %3E
27         {             %7B
28                       %20